### ISSUE TITLE
Conflict execution when multiple format on save is triggered

### ISSUE THREAD

**Issue by tomy0000000** [Aeron/Black.novaextension#1]
I have both black and isort install, and both of them have "format on save" feature enabled.

Occasionally, when one of the format is triggered, says black, the modification will trigger isort formating, which will then back trigger black, and the loop goes on until I manually disable one of the extension.
Sometimes, this does not happen, but yield an incorrect code. (duplicate lines with wrong indentation or syntax error)

Maybe there should be a callback to coordinate the priority of the trigger. Although IMHO, this probably should be solved on Nova's side.

**Comment by Aeron** [comment]
Thanks. I see what I can do about it. Unfortunately, I’m not using Nova for anything these days because even the Python syntax is not as good as it should be.

**Comment by Aeron** [comment]
Ok, now this should cause no trouble. I rewrote both formatters (for Black and isort extensions) a bit to use promises, so Nova should handle all pre-save events properly. It means no excessive saving or infinite loops anymore.

New versions are already available in the extension library.

Let me know if anything.
