### ISSUE TITLE
Plugin should only reformat Python files

### ISSUE THREAD

**Issue by guillaumealgis** [Aeron/Black.novaextension#3]
Currently, the extension is only activated when a Python file is opened (which is fine) but once it is activated (and "reformat on save" is enabled) it will try and reformat every file that is saved (regardless of the file content).

This is okay-ish for most files because Black won't know what to do with it, but for (some?) JSON files Black will reformat the content on save, which is unexpected (I wasn't aware Black was able to reformat JSON files, that's probably a side-effect of JSON and Python dict sharing a similar syntax).

I think the extension should check the current buffer syntax (Python vs something else) before reformatting on save.

**Comment by Aeron** [comment]
Yup, you’re right. I removed that extra syntax check right before version 1.0.0, thinking it was redundant because the extension configuration explicitly has the activation event. My bad, I’ll fix it ASAP.

**Comment by Aeron** [comment]
The [isort](https://github.com/Aeron/isort.novaextension) extension also had this issue. Both extensions got an update (version 1.0.1) and are fixed by now. Thanks for the report.

**Comment by guillaumealgis** [comment]
Great, thanks @Aeron for the super quick fix!
