### ISSUE TITLE
Stubs files (.pyi) are not formatted correctly

### ISSUE THREAD

**Issue by guillaumealgis** [Aeron/Black.novaextension#4]
Black uses different rules to format stubs (`.pyi`) files : https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#typing-stub-files

Because the extension is running black by passing the python code on stdin (instead of passing the file's path as argument), the file extension cannot be picked up by Black, and the format used is not the right one.

```
Black[15:38:15.277000] Running /Users/guillaume/foo/venv/bin/black --quiet -
```

For example :

<details> 
  <summary>Expected formatting</summary>
  <pre lang="python">
from concurrent.futures import Future
from typing import Any

from _typeshed import Incomplete
from requests import Session

def wrap(self, sup, background_callback, *args_, **kwargs_): ...

PICKLE_ERROR: str

class FuturesSession(Session):
    executor: Incomplete
    session: Incomplete

    def __init__(
        self,
        executor: Incomplete | None = ...,
        max_workers: int = ...,
        session: Session | None = ...,
        adapter_kwargs: Incomplete | None = ...,
        *args,
        **kwargs,
    ) -> None: ...
    def request(self, *args: Any, **kwargs: Any) -> Future:
        pass
    def close(self) -> None: ...
    def get(self, url, **kwargs): ...
    def options(self, url, **kwargs): ...
    def head(self, url, **kwargs): ...
    def post(
        self,
        url,
        data: Incomplete | None = ...,
        json: Incomplete | None = ...,
        **kwargs,
    ): ...
    def put(self, url, data: Incomplete | None = ..., **kwargs): ...
    def patch(self, url, data: Incomplete | None = ..., **kwargs): ...
    def delete(self, url, **kwargs): ...
  </code>
</details>

<details> 
  <summary>Actual Black.novaextension formatting</summary>
  <pre lang="python">
from concurrent.futures import Future
from typing import Any

from _typeshed import Incomplete
from requests import Session

def wrap(self, sup, background_callback, *args_, **kwargs_):
    ...

PICKLE_ERROR: str

class FuturesSession(Session):
    executor: Incomplete
    session: Incomplete

    def __init__(
        self,
        executor: Incomplete | None = ...,
        max_workers: int = ...,
        session: Session | None = ...,
        adapter_kwargs: Incomplete | None = ...,
        *args,
        **kwargs,
    ) -> None:
        ...

    def request(self, *args: Any, **kwargs: Any) -> Future:
        pass

    def close(self) -> None:
        ...

    def get(self, url, **kwargs):
        ...

    def options(self, url, **kwargs):
        ...

    def head(self, url, **kwargs):
        ...

    def post(
        self,
        url,
        data: Incomplete | None = ...,
        json: Incomplete | None = ...,
        **kwargs,
    ):
        ...

    def put(self, url, data: Incomplete | None = ..., **kwargs):
        ...

    def patch(self, url, data: Incomplete | None = ..., **kwargs):
        ...

    def delete(self, url, **kwargs):
        ...
  </code>
</details>

**Comment by Aeron** [comment]
Hmm, I see. Ok, I’ll see what I can do about it. Does VSCode, for example, behave the same? If you have any experience with it.

**Comment by guillaumealgis** [comment]
@Aeron nope sorry, I'm using Nova exclusively, I have no other editor I could compare this behavior to :/

**Comment by Aeron** [comment]
Ok, no worries. I’ll figure something out. I don’t use `.pyi` files, so I’ve never faced such an issue. But it should be easy to reproduce.
